version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - .:/var/www/html
        ports:
            - '${APP_PORT:-8099}:80'
